#-------------------------------
# General Site Settings
title: Clube da Joice
logo: logo.png
description: Um pouquinho de literatura no seu dia a dia.


#-------------------------------
# Author Settings
author:
  name: Joice Marques
  image: 01.jpg
  say-hello: Bem-vindo(a)! <br> Sou <strong>Joice Marques</strong>
  bio: Sou apaixonada pelo universo literário. Amo ler, pois os livros abrem portas para mundos diferentes a cada vez que decidimos lê-los. A música e as artes em geral são minhas companheiras ❤️. <br>Quer saber um pouco mais sobre seu livro favorito? Procure aqui um post sobre ele.


#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/joice.club
youtube: https://www.youtube.com/channel/UCkxWCZlGgXaaqLYQA7rfVSg
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
# instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
# instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
